# Generated by Django 2.1.5 on 2019-06-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('image', models.TextField()),
                ('model_type', models.TextField()),
                ('result', models.TextField()),
            ],
        ),
    ]
